addr: 127.0.0.1:8080
streamaddr: 127.0.0.1:9090
logger: logger.xml
db:
  instances:
    master: 
      driver: mysql
      url: root:123456@tcp(127.0.0.1:3306)/user_login?charset=utf8
pwdsecret: EV3KI$a12DAHWAda
factorlangth: 8
tokensecret: M976*fdaeQWdse2W
tokenexpiretime: 6000