// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login_guide/login_guide.proto

package userlogin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type LoginRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceId             string   `protobuf:"bytes,3,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Signature            string   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_297f1529e65767ff, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *LoginRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type TokenReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenReply) Reset()         { *m = TokenReply{} }
func (m *TokenReply) String() string { return proto.CompactTextString(m) }
func (*TokenReply) ProtoMessage()    {}
func (*TokenReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_297f1529e65767ff, []int{1}
}

func (m *TokenReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenReply.Unmarshal(m, b)
}
func (m *TokenReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenReply.Marshal(b, m, deterministic)
}
func (m *TokenReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenReply.Merge(m, src)
}
func (m *TokenReply) XXX_Size() int {
	return xxx_messageInfo_TokenReply.Size(m)
}
func (m *TokenReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenReply.DiscardUnknown(m)
}

var xxx_messageInfo_TokenReply proto.InternalMessageInfo

func (m *TokenReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenCheckRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenCheckRequest) Reset()         { *m = TokenCheckRequest{} }
func (m *TokenCheckRequest) String() string { return proto.CompactTextString(m) }
func (*TokenCheckRequest) ProtoMessage()    {}
func (*TokenCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_297f1529e65767ff, []int{2}
}

func (m *TokenCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCheckRequest.Unmarshal(m, b)
}
func (m *TokenCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCheckRequest.Marshal(b, m, deterministic)
}
func (m *TokenCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCheckRequest.Merge(m, src)
}
func (m *TokenCheckRequest) XXX_Size() int {
	return xxx_messageInfo_TokenCheckRequest.Size(m)
}
func (m *TokenCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCheckRequest proto.InternalMessageInfo

func (m *TokenCheckRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type TokenCheckReply struct {
	Flag                 int32    `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenCheckReply) Reset()         { *m = TokenCheckReply{} }
func (m *TokenCheckReply) String() string { return proto.CompactTextString(m) }
func (*TokenCheckReply) ProtoMessage()    {}
func (*TokenCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_297f1529e65767ff, []int{3}
}

func (m *TokenCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCheckReply.Unmarshal(m, b)
}
func (m *TokenCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCheckReply.Marshal(b, m, deterministic)
}
func (m *TokenCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCheckReply.Merge(m, src)
}
func (m *TokenCheckReply) XXX_Size() int {
	return xxx_messageInfo_TokenCheckReply.Size(m)
}
func (m *TokenCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCheckReply proto.InternalMessageInfo

func (m *TokenCheckReply) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "userlogin.LoginRequest")
	proto.RegisterType((*TokenReply)(nil), "userlogin.TokenReply")
	proto.RegisterType((*TokenCheckRequest)(nil), "userlogin.TokenCheckRequest")
	proto.RegisterType((*TokenCheckReply)(nil), "userlogin.TokenCheckReply")
}

func init() {
	proto.RegisterFile("login_guide/login_guide.proto", fileDescriptor_297f1529e65767ff)
}

var fileDescriptor_297f1529e65767ff = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xad, 0xee, 0xae, 0x76, 0x58, 0x10, 0x83, 0x7f, 0x4a, 0x59, 0x41, 0x02, 0x82, 0x5e,
	0x2a, 0xe8, 0x59, 0x10, 0x3c, 0xe8, 0x82, 0xa7, 0xa0, 0x67, 0xa9, 0x9b, 0x31, 0x86, 0x2d, 0x4d,
	0x4d, 0x52, 0x45, 0xf0, 0x63, 0xfa, 0x81, 0x24, 0xb3, 0xdd, 0x6d, 0x10, 0xbd, 0x78, 0x9b, 0x37,
	0xbf, 0x97, 0xc9, 0xe4, 0x05, 0x0e, 0x2b, 0xa3, 0x74, 0xfd, 0xa8, 0x5a, 0x2d, 0xf1, 0x2c, 0xaa,
	0x8b, 0xc6, 0x1a, 0x6f, 0x58, 0xda, 0x3a, 0xb4, 0xd4, 0xe6, 0x9f, 0x30, 0xbe, 0x0b, 0x85, 0xc0,
	0xd7, 0x16, 0x9d, 0x67, 0xfb, 0x30, 0x0a, 0x70, 0x2a, 0xb3, 0xe4, 0x28, 0x39, 0x49, 0x45, 0xa7,
	0x58, 0x0e, 0x5b, 0x4d, 0xe9, 0xdc, 0xbb, 0xb1, 0x32, 0x5b, 0x27, 0xb2, 0xd2, 0x81, 0x49, 0x7c,
	0xd3, 0x33, 0x9c, 0xca, 0x6c, 0x63, 0xc1, 0x96, 0x9a, 0x4d, 0x20, 0x75, 0x5a, 0xd5, 0xa5, 0x6f,
	0x2d, 0x66, 0x03, 0x82, 0x7d, 0x83, 0x73, 0x80, 0x7b, 0x33, 0xc7, 0x5a, 0x60, 0x53, 0x7d, 0xb0,
	0x5d, 0x18, 0xfa, 0xa0, 0xba, 0xab, 0x17, 0x82, 0x9f, 0xc2, 0x0e, 0x79, 0xae, 0x5f, 0x70, 0x36,
	0x5f, 0xae, 0xf9, 0xbb, 0xf5, 0x18, 0xb6, 0x63, 0x6b, 0x98, 0xc9, 0x60, 0xf0, 0x5c, 0x95, 0x8a,
	0x7c, 0x43, 0x41, 0xf5, 0xf9, 0x57, 0x02, 0x9b, 0x37, 0x16, 0xd1, 0xa3, 0x65, 0x57, 0x30, 0x7e,
	0x70, 0x68, 0x05, 0x2a, 0xed, 0x82, 0x3e, 0x28, 0x56, 0xd9, 0x14, 0x71, 0x30, 0xf9, 0x5e, 0x04,
	0xfa, 0x9d, 0xf9, 0x1a, 0xbb, 0x84, 0x34, 0x4c, 0x20, 0xf3, 0x3f, 0x8e, 0xdf, 0x76, 0x11, 0xd0,
	0xce, 0x6c, 0xf2, 0xd3, 0x16, 0xbf, 0x3a, 0xcf, 0xff, 0xa0, 0x34, 0xe9, 0x69, 0x44, 0x9f, 0x7b,
	0xf1, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x05, 0x85, 0x3a, 0x4a, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	UserRegister(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error)
	UserLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error)
	TokenCheck(ctx context.Context, in *TokenCheckRequest, opts ...grpc.CallOption) (*TokenCheckReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) UserRegister(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, "/userlogin.Greeter/UserRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) UserLogin(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenReply, error) {
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, "/userlogin.Greeter/UserLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) TokenCheck(ctx context.Context, in *TokenCheckRequest, opts ...grpc.CallOption) (*TokenCheckReply, error) {
	out := new(TokenCheckReply)
	err := c.cc.Invoke(ctx, "/userlogin.Greeter/TokenCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	UserRegister(context.Context, *LoginRequest) (*TokenReply, error)
	UserLogin(context.Context, *LoginRequest) (*TokenReply, error)
	TokenCheck(context.Context, *TokenCheckRequest) (*TokenCheckReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) UserRegister(ctx context.Context, req *LoginRequest) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (*UnimplementedGreeterServer) UserLogin(ctx context.Context, req *LoginRequest) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (*UnimplementedGreeterServer) TokenCheck(ctx context.Context, req *TokenCheckRequest) (*TokenCheckReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenCheck not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userlogin.Greeter/UserRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).UserRegister(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userlogin.Greeter/UserLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).UserLogin(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_TokenCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).TokenCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userlogin.Greeter/TokenCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).TokenCheck(ctx, req.(*TokenCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userlogin.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRegister",
			Handler:    _Greeter_UserRegister_Handler,
		},
		{
			MethodName: "UserLogin",
			Handler:    _Greeter_UserLogin_Handler,
		},
		{
			MethodName: "TokenCheck",
			Handler:    _Greeter_TokenCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login_guide/login_guide.proto",
}
